# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickContact' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod "QRCode", :git => "https://github.com/aschuch/QRCode.git"

  # Pods for QuickContact

  target 'QuickContactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickContactUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
